# Lists and Arrays
To better understand data science, let's explore how data is stored and manipulated. For example, a list is really a Python object and overhead compared to compiled languages like C. While the list is vey flexible. It does come at a cost. The array, on the other hand, essentially contains a single pointer to one block of data. Much more efficient and has many other advantages. 

### Creating lists

In [ ]:
# create a list containing "Python", 2025, True and asssign it to a variable: my_list
my_list = ["Python", 2025, True]
 
# print my_list
print(my_list)

NumPy arrays are a more resource-efficient alternative to lists that also come equipped with tools for data science. Both lists and Numpy arrays can be used to construct more complex data structures such as dictionaries and data frames. 

### Beyond Sublists with Numpy and `ndarray`
NumPy is a Python library for working with arrays. NumPy is short for "Numerical Python".

In [1]:
#!conda install numpy
import numpy as np

# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [2]:
## what shape is your array?
a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)
print('Shape :','\n',a.shape)
print('Rows = ',a.shape[0])
print('Columns = ',a.shape[1])

# you can reshape your arrays, no problem
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows =  2
Columns =  3


array([[ 3,  6],
       [ 9, 12]])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

NumPy uses a character to represent each of the following data types:


- i = integer
- b = boolean
- u = unsigned integer
- f = float
- c = complex float
- m = timedelta
- M = datetime
- O = object
- S = string

## Most Importantly, the Pandas DataFrame

In [2]:
import pandas as pd 

mls_df = pd.read_csv('https://raw.githubusercontent.com/cbtn-data-science-ml/python-for-data-analysis/main/datasets/mls_salaries.csv')
mls_df

club last_name first_name position  base_salary  guaranteed_compensation
0    ATL   Almiron     Miguel        M    1912500.0               2297000.00
1    ATL   Ambrose      Mikey        D      65625.0                 65625.00
2    ATL      Asad      Yamil        M     150000.0                150000.00
3    ATL     Bloom       Mark        D      99225.0                106573.89
4    ATL  Carleton     Andrew        F      65000.0                 77400.00
..   ...       ...        ...      ...          ...                      ...
610  VAN   Teibert    Russell        M     126500.0                194000.00
611  VAN  Tornaghi      Paolo       GK      80000.0                 80000.00
612  VAN    Waston    Kendall        D     350000.0                368125.00
613  NaN       NaN        NaN      NaN          NaN                      NaN
614  VAN  Williams    Sheanon        D     175000.0                184000.00

[615 rows x 6 columns]