# Creating Numpy and Manipulating Arrays

In [1]:
import numpy as np

In [6]:
# There are several ways to create Numpy arrays:

# create a 2-dimensional array from a list of lists
a = np.array([[1,2],[3,4]])
# create an array of zeros
b = np.zeros(8)
# create an array of ones
c = np.ones(8)

#a
#b
c

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
# typecasting arrays
d = np.ones(5, dtype = int)
d

array([1, 1, 1, 1, 1])

In [11]:
# evenly spaced values
e = np.linspace(0, 50, 100, dtype = int)
e

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16,
       17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25,
       25, 26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33,
       34, 34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42,
       42, 43, 43, 44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 50])

In [13]:
# 2 dimensional array with rand values
f = np.random.rand(2, 2)
f

array([[0.12992974, 0.83288335],
       [0.09793624, 0.95908672]])

In [14]:
# create an array from a list
g = np.array([1, 2, 3])

# print the array
print(g)
# access the first element of the array
print(g[0])
# slice the first two elements of the array
print(g[0:2])

[1 2 3]
1
[1 2]


# Manipulating Arrays

In [19]:
# You can use the "reshape" method to change the shape of a Numpy array without changing the data.
a = np.array([1, 2, 3, 4, 5, 6])
a.shape # tells me the shape
a.shape = (2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# reshape the array into a 3x2 matrix
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# reshape the array into a 2x3 matrix
c = a.reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

# Transposing Numpy arrays

In [23]:
# You can use the "T" attribute to transpose a Numpy array. This flips the array along its diagonal, so that rows become columns and vice versa.
d = b.T
# transpose the array
d

array([[1, 3, 5],
       [2, 4, 6]])