# Basic Operations with Numpy Arrays

In [1]:
import numpy as np

In [4]:
# You can perform mathematical operations on Numpy arrays element-wise.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [10]:
# add the arrays element-wise
c = a + b
c

array([5, 7, 9])

In [11]:
# subtract the arrays element-wise
d = a - b
c

array([5, 7, 9])

In [12]:
# multiply the arrays element-wise
e = a * b
e

array([ 4, 10, 18])

In [13]:
# divide the arrays element-wise
f = a / b
f

array([0.25, 0.4 , 0.5 ])