# Numpy array methods and functions

In [1]:
import numpy as np

In [4]:
# You can use Numpy's aggregate functions to perform operations across the entire array.
a = np.array([[1, 2], [3, 4]])


In [6]:
# find the minimum value of the array
np.min(a)

1

In [7]:
# find the maximum value of the array
np.max(a)

4

In [8]:
# calculate the mean of the array
np.mean(a)

2.5

In [9]:
# calculate the median of the array
np.median(a)

2.5

In [10]:
# calculate the standard deviation of the array
np.std(a)

1.118033988749895

In [11]:
# calculate the sum of the array
np.sum(a)

10

In [14]:
# calculate the product of the array
np.prod(a)

24

# Statistical functions

In [16]:
# You can use Numpy's statistical functions to calculate statistical measures of an array.
b = np.array([1, 2, 3, 4, 5])

# calculate the correlation coefficient of the array
np.corrcoef(b)

1.0

In [17]:
# calculate the covariance of the array
np.cov(a)

array([[0.5, 0.5],
       [0.5, 0.5]])

# Linear algebra functions

In [14]:
# Linear algebra functions

# You can use Numpy's linear algebra functions to perform operations such as matrix multiplication.


In [18]:
c = np.array([[1,2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [19]:
result = np.dot(a, a) # give dot product of two matices
result

array([[ 7, 10],
       [15, 22]])

In [20]:
a @ a # also gives a dot product for two matrices

array([[ 7, 10],
       [15, 22]])